# docker-compose.yml

version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CORS_ORIGIN=http://localhost:3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE_URL=https://api.openai.com/v1
      - LLM_MODEL_NAME=gpt-4o-mini
      - GOOGLE_SEARCH_API_KEY=${GOOGLE_SEARCH_API_KEY}
      - GOOGLE_SEARCH_ENGINE_ID=${GOOGLE_SEARCH_ENGINE_ID}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - CHROMA_DB_URL=http://chroma:8000
    volumes:
      - ./uploads:/app/packages/api/uploads
    depends_on:
      - chroma

  web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - api

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma

volumes:
  chroma-data:
